# Jekyll configuration

title: sevennight(7夜)
description: Github博客地址<br/>http://7ye.xyz<br/>博客园地址<br/>http://www.sevennight.cn
signature: 年华一去不复返，时光逝去再难回。

#author message
author:
  github: https://github.com/7ye
  name: SevenNight

# url is currently only used only for the RSS feed in feed.xml
url: http://7ye.xyz

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ""
#cdn Picture storage address
picurl: http://7u2sny.com1.z0.glb.clouddn.com

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
comments: true

#Open catalog Structure
catalog : true

permalink: /:year/:month/:title
permalink: /:year/:month/:day/:title
paginate: 10


markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']


